### ISSUE TITLE
`gl-Class-variants` and other variants

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/thema-css#2]
Do we simply override some styles? Or do we write it like `gl-Header gl-Header-variant`?

```css
.gl-Header {
    color: red;

    &-blue {
        color: blue;
    }
}
```
